--- #YAML:1.0
name: Text-Indent
version: 0.1
license: perl
distribution_type: module
requires:
  Class::MethodMaker: 1.12
  Params::Validate: 0.5
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Text::Indent:
    file: lib/Text/Indent.pm
    version: 0.001
generated_by: Module::Build version 0.21
